# 03error_correction.sub
#
#
# Specify the HTCondor Universe
universe = docker
docker_image = qiime2/core:2018.6

log = 03error_correction_$(Cluster).log
error = 03error_correction_$(Cluster)_$(Process).err
requirements = (OpSysMajorVer == 7) && (Target.HasGluster == true)
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = executables/03error_correction.sh
arguments = $(settings)
output = 03error_correction_$(Cluster).out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/amlinz/trimmed_100.tar.gz,manifest.txt
transfer_output_files = $(settings).qza 
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.

request_cpus = 1
request_memory = 1GB
request_disk = 500MB
#
# Tell HTCondor to run every fastq file in the provided list:
queue settings from error_settings.txt

